package entidades;
// Generated 14-jul-2017 8:45:15 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private Integer id;
     private Account account;
     private String name;
     private Date datecreation;
     private byte status;
     private Set ordersdetails = new HashSet(0);

    public Orders() {
    }

	
    public Orders(Account account, String name, Date datecreation, byte status) {
        this.account = account;
        this.name = name;
        this.datecreation = datecreation;
        this.status = status;
    }
    public Orders(Account account, String name, Date datecreation, byte status, Set ordersdetails) {
       this.account = account;
       this.name = name;
       this.datecreation = datecreation;
       this.status = status;
       this.ordersdetails = ordersdetails;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDatecreation() {
        return this.datecreation;
    }
    
    public void setDatecreation(Date datecreation) {
        this.datecreation = datecreation;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public Set getOrdersdetails() {
        return this.ordersdetails;
    }
    
    public void setOrdersdetails(Set ordersdetails) {
        this.ordersdetails = ordersdetails;
    }




}


