package entidades;
// Generated 14-jul-2017 8:45:15 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private Partner partner;
     private String name;
     private BigDecimal price;
     private int quantity;
     private String description;
     private String photo;
     private byte feature;
     private Ordersdetail ordersdetail;

    public Product() {
    }

	
    public Product(Category category, Partner partner, String name, BigDecimal price, int quantity, String description, String photo, byte feature) {
        this.category = category;
        this.partner = partner;
        this.name = name;
        this.price = price;
        this.quantity = quantity;
        this.description = description;
        this.photo = photo;
        this.feature = feature;
    }
    public Product(Category category, Partner partner, String name, BigDecimal price, int quantity, String description, String photo, byte feature, Ordersdetail ordersdetail) {
       this.category = category;
       this.partner = partner;
       this.name = name;
       this.price = price;
       this.quantity = quantity;
       this.description = description;
       this.photo = photo;
       this.feature = feature;
       this.ordersdetail = ordersdetail;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Partner getPartner() {
        return this.partner;
    }
    
    public void setPartner(Partner partner) {
        this.partner = partner;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public byte getFeature() {
        return this.feature;
    }
    
    public void setFeature(byte feature) {
        this.feature = feature;
    }
    public Ordersdetail getOrdersdetail() {
        return this.ordersdetail;
    }
    
    public void setOrdersdetail(Ordersdetail ordersdetail) {
        this.ordersdetail = ordersdetail;
    }




}


